"""add_email_verification_fields

Revision ID: 3b29cd06b7e3
Revises: 
Create Date: 2025-11-13 00:57:44.819490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b29cd06b7e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### FIXED: Only add the new columns - ignore all drops/recreates ###
    # Alembic autogenerated full schema drop/recreate due to model/DB mismatch,
    # but we only need to add the verified fields. No drops to avoid FK errors.
    op.add_column('users', sa.Column('verified', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('users', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end FIXED commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verified_at')
    op.drop_column('users', 'verified')
    # ### end Alembic commands ###